%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\Dropbox\Covid_19_FIT_Modelle\RKI_COVID19.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/04/06 12:53:52

%% Initialize variables.
filename = 'D:\Dropbox\Covid_19_FIT_Modelle\RKI_COVID19_07_04.csv';
delimiter = ',';

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,6,7,8,10,12,13]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,6,7,8,10,12,13]);
rawCellColumns = raw(:, [2,3,4,5,9,11]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
RKICOVID1 = table;
RKICOVID1.IdBundesland = cell2mat(rawNumericColumns(:, 1));
RKICOVID1.Bundesland = rawCellColumns(:, 1);
RKICOVID1.Landkreis = rawCellColumns(:, 2);
RKICOVID1.Altersgruppe = rawCellColumns(:, 3);
RKICOVID1.Geschlecht = rawCellColumns(:, 4);
RKICOVID1.AnzahlFall = cell2mat(rawNumericColumns(:, 2));
RKICOVID1.AnzahlTodesfall = cell2mat(rawNumericColumns(:, 3));
RKICOVID1.ObjectId = cell2mat(rawNumericColumns(:, 4));
RKICOVID1.Meldedatum = rawCellColumns(:, 5);
RKICOVID1.IdLandkreis = cell2mat(rawNumericColumns(:, 5));
RKICOVID1.Datenstand = rawCellColumns(:, 6);
RKICOVID1.NeuerFall = cell2mat(rawNumericColumns(:, 6));
RKICOVID1.NeuerTodesfall = cell2mat(rawNumericColumns(:, 7));

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me rawNumericColumns rawCellColumns R;