#!/bin/bash
#$ -N RKI_IA
#$ -t 1:9500
#$ -l mem=5G
#$ -m n
#$ -q ni.q
#$ -l h='!(ramsauer.ikw.uni-osnabrueck.de|vector.cv.uni-osnabrueck.de|righty.ni.uni-osnabrueck.de)'
#$ -wd /net/store/ni/users/leffenberger/BSTIM-Covid19/src
#$ -e /net/store/ni/users/leffenberger/BSTIM-Covid19/logs/e_$TASK_ID.txt
#$ -o /net/store/ni/users/leffenberger/BSTIM-Covid19/logs/o_$TASK_ID.txt
#$ -pe default 4

echo "Running job ${JOB_ID}, task ${SGE_TASK_ID} on `hostname`."

mkdir "/tmp/${JOB_ID}_${SGE_TASK_ID}"

source /net/store/ni/users/leffenberger/BSTIM-Covid19/.venv/bin/activate
THEANO_FLAGS="base_compiledir=/tmp/${JOB_ID}_${SGE_TASK_ID}/,floatX=float32,device=cpu,openmp=True,mode=FAST_RUN,warn_float64=warn" OMP_NUM_THREADS=8  python3 sample_ia_effects_window.py
